StudentBundle\Entity\Student:
    type: entity
    table: student
    repositoryClass: StudentBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        sexe:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateNaissance:
            type: datetime
            nullable: false
            column: date_naissance
        idCategory:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_category
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: students
            joinColumn:
                name: id_category
                referencedColumnName: id
    lifecycleCallbacks: {  }