StudentBundle\Entity\Student:
    type: entity
    repositoryClass: StudentBundle\Repository\StudentRepository
    table: student
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 100
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 100
            fixed: false
        sexe:
            type: string
            nullable: false
            length: 10
            fixed: false
        dateNaissance:
            type: date
            nullable: false
            column: date_naissance
    lifecycleCallbacks: {  }
